version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chatroom-server
    ports:
      - "5050:5050"
    volumes:
      # Persist the SQLite database file
      - sqlite_data:/app/instance
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local